### ISSUE TITLE
Incorrect slot numbers used when method follows a read-only property

### ISSUE THREAD

**Issue by wjk** [kant2002/WinFormsComInterop#16]
Consider the following code:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace Repro
{
    [Guid("95627282-E95D-4B4B-AD4E-94E440D2A92C"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    interface ISayHello
    {
        int HelloCount { get; }
        void SayHello(string toWhom);
    }
}
```

When I add this code to my project and add the `RuntimeCallableAttribute`, the source generator uses a slot number of 3 for `HelloCount` (as it should), but a slot number of 5 for `SayHello`. This will more-or-less guarantee an AccessViolationException whenever you call `SayHello`. I don’t know why this happens ([since the code that increments the slot number for a setter method is skipped if there is none](https://github.com/kant2002/WinFormsComInterop/blob/22cb08a799420fa652a5efa086e6871e7c17de95/WinFormsComInterop.SourceGenerator/Generator.cs#L704-L711)). I am using SourceGenerator version 0.2.8. Thanks for looking into this for me!

**Comment by kant2002** [comment]
You can try with 0.2.9
