### ISSUE TITLE
dotnet add package WinFormsComInterop failed

### ISSUE THREAD

**Issue by cwing2019** [kant2002/WinFormsComInterop#19]
execute " dotnet add package WinFormsComInterop "
says:

info :   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6
d082ae6d/_packaging/fe324174-469a-4296-a9cb-1fd885bb6f2b/nuget/v3/registrations2
-semver2/winformscominterop/index.json 1726 毫秒
info :   GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082a
e6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/registrations2-semv
er2/winformscominterop/index.json
info :   GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082a
e6d/_packaging/fe324174-469a-4296-a9cb-1fd885bb6f2b/nuget/v3/registrations2-semv
er2/winformscominterop/index.json
info :   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6
d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/registrations2
-semver2/winformscominterop/index.json 512 毫秒
info :   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6
d082ae6d/_packaging/fe324174-469a-4296-a9cb-1fd885bb6f2b/nuget/v3/registrations2
-semver2/winformscominterop/index.json 996 毫秒

**Comment by kant2002** [comment]
Make sure that your Nuget.config has official Nuget feed. For example
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
 </packageSources>
</configuration>

```

**Comment by cwing2019** [comment]
IT WORKS

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
    
  </packageSources>
</configuration>

PLUS ,I uncommented the add key="dotnet6"
