### ISSUE TITLE
Support for DragDrop is incomplete

### ISSUE THREAD

**Issue by sudongg** [kant2002/WinFormsComInterop#21]
Hi,
After testing, the DragOver event can be triggered. But `e.Data.GetDataPresent() ` has no effect,
DragDrop and DragEnter events are never triggered.

This project has not been updated for 4 months. I don't know whether it will continue.

**Comment by kant2002** [comment]
There not much to do with this project anymore, and my best hopes that WinForms would move towards supporting IL trimming. If you have specific repo, I can take a look.

**Comment by sudongg** [comment]
Hi，
I modified the samplewindowsforms example:

https://github.com/sudongg/WinFormsComInterop.git

I added the form1.cs file, code:
```
  public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            Load += (s, e) =>
            {
                AllowDrop = true;

                DragOver += (s, e) =>
                {      
                    //DragOver  can be triggered
                    e.Effect = DragDropEffects.Link;
                    //MessageBo.Show("DragOver");

                    ////Using the following code will cause a System.NullReferenceException
                    //if (e.Data.GetDataPresent(DataFormats.FileDrop))
                    //{
                    //    MessageBox.Show("DragOver");
                    //}
                };

                DragEnter += (s, e) =>
                {
                    //Unable to trigger  DragEnter event
                    MessageBox.Show("DragEnter");
                };

                DragDrop += (s, e) =>
                {  
                    //Unable to trigger  DragDrop event
                    MessageBox.Show("DragDrop");
                };
            };
        }
    }
```


You can download the zip file and run the samplewindowsforms  example to see the problem.
Drag and drop the file to the window after running, you can trigger DragOver, but you cannot trigger DragEnter and DragDrop events, and System.NullReferenceException when trying to get drag data;

**Comment by kant2002** [comment]
@sudongg can you try your sample with .NET 7.0? This part is using ComWrappers and I hope that issue just `magically` disappear

**Comment by kant2002** [comment]
WinForms on .NET 7 now supports drag/drop in the NativeAOT, if something would not work, let me know. Once https://github.com/dotnet/winforms/pull/7145 lands no need for using this library specifically for WinForms
