### ISSUE TITLE
FolderBrowserDialog  BUG

### ISSUE THREAD

**Issue by wsxhm** [kant2002/WinFormsComInterop#22]
close the FolderBrowserDialog  throw Exception   net6.0

![65SS@E7QHY4DZVOLZ5K~ IM](https://user-images.githubusercontent.com/20971139/141667431-19365e5e-0bfb-479f-95d1-4802c8533237.png)

![image](https://user-images.githubusercontent.com/20971139/141667454-0c76981e-5788-4ac4-85dc-f3085a5d86b0.png)

![image](https://user-images.githubusercontent.com/20971139/141667493-a7c37dfe-a2fa-4973-97a6-a2ead7ee7781.png)

**Comment by kant2002** [comment]
Is this .NET 5 or .NET 6, I think I have this bug fixed in .NET 6, if not, I would recommend you to custom build WinForms which is very easy IMO.

**Comment by timiil** [comment]
should be .NET 6, the 'OpenFileDialog' is also throw an exception :

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'WinFormsComInterop.IExternalObject' to type 'IFileOpenDialog'.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void* toTypeHnd, Object obj)
   在 System.Windows.Forms.OpenFileDialog.CreateVistaDialog()
   在 System.Windows.Forms.FileDialog.TryRunDialogVista(IntPtr hWndOwner, Boolean& returnValue)
   在 System.Windows.Forms.FileDialog.RunDialog(IntPtr hWndOwner)
   在 System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   在 System.Windows.Forms.CommonDialog.ShowDialog()
   在 BYHKTools.frmDevice.<.ctor>b__3_7(Object _, EventArgs _) 在 D:\code\faceconsole2\BYHKTools\frmDevice.cs 中: 第 211 行
   在 System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Comment by darkguy2008** [comment]
> Is this .NET 5 or .NET 6, I think I have this bug fixed in .NET 6, if not, I would recommend you to custom build WinForms which is very easy IMO.

Any ideas on how to build custom WinForms ourselves? You mention it twice in some other issues but I fail to see how easy it is without at least a pointer to some page or link explaining how easy it is. Much appreciated!

**Comment by kant2002** [comment]
> Any ideas on how to build custom WinForms ourselves? 

you literally 
1. clone https://github.com/dotnet/winforms
2. Run build.cmd
3. Add produced binaries as reference
Location of outputs are described on build instructions page https://github.com/dotnet/winforms/blob/main/docs/building.md#build-outputs

**Comment by darkguy2008** [comment]
> > Any ideas on how to build custom WinForms ourselves?
> 
> you literally
> 
> 1. clone https://github.com/dotnet/winforms
> 2. Run build.cmd
> 3. Add produced binaries as reference
>    Location of outputs are described on build instructions page https://github.com/dotnet/winforms/blob/main/docs/building.md#build-outputs

Hey, thanks for your quick answer! I had seen that repo but I was skeptical that it would be just like you say and that the repo was compatible and/or had the full source code to make a working Windows.Forms implementation. Usually Microsoft code is full of riddles and sometimes it's the equivalent of attempting to build a linux kernel 😂 it's kinda surprising, so I'll give that a try, thank you!

Assuming it works though, this means that it would solve the COM issues when using this lib and/or NativeAOT with Windows Forms, right?

**Comment by kant2002** [comment]
> this means that it would solve the COM issues when using this lib

If you take latest `main` branch. Apply https://github.com/dotnet/winforms/pull/5319 on top of it, that specific issue would be gone. If you have another issue in another control, for me this is separate issue and please post separately/

Aforementioned PR is about to get finished, so expect to just use main branch. Overall WinForms team positive to AOT of WinForms and I expect that this project would dissolve itself, since WinForms would be ready for AOT by itself. 

Just in case you would be interested. If you have bug with Windows Forms it is trivial to contribute. Guys on the project good to work with, even if they strict about quality.

**Comment by kant2002** [comment]
Latest WinForms in .NET 7 will have a fix. It is not possible to have fix in .NET 6 so I will close issue.
