### ISSUE TITLE
could not launch sample wpf application 

### ISSUE THREAD

**Issue by unofficialdev** [kant2002/WinFormsComInterop#23]
trying to run sample wpf application throws an exception
![Image 1](https://user-images.githubusercontent.com/43975116/147808727-decc18ce-68c5-4b82-b0a9-599025f34540.png)

**Comment by kant2002** [comment]
WPF is work in progress which I halt because slow response time from WPF team. https://github.com/dotnet/runtime/pull/63219 maybe unlock me, so cross your fingers

**Comment by kant2002** [comment]
I would close this in favor of #1 since this is essentially the same.
