### ISSUE TITLE
 Windows Forms is not supported or recommended

### ISSUE THREAD

**Issue by zhzhwcn** [kant2002/WinFormsComInterop#39]
Microsoft.NET.RuntimeIdentifierInference.targets(176,5): error NETSDK1175:  Windows Forms is not supported or recommended with trimming enabled. Please go to https://aka.ms/dotnet-illink/windows-forms for more details.

**Comment by zhzhwcn** [comment]
PS E:\dotnet\winformstest> dotnet --version
6.0.202
PS E:\dotnet\winformstest> dotnet new winforms
已成功创建模板“Windows 窗体应用”。

正在处理创建后操作...
在 E:\dotnet\winformstest\winformstest.csproj 上运行 “dotnet restore”...
  正在确定要还原的项目…
  已还原 E:\dotnet\winformstest\winformstest.csproj (用时 56 ms)。
已成功还原。

PS E:\dotnet\winformstest> dotnet add package WinFormsComInterop
  正在确定要还原的项目…
  Writing C:\Users\zhzhw\AppData\Local\Temp\tmp8638.tmp
info : 正在将包“WinFormsComInterop”的 PackageReference 添加到项目“E:\dotnet\winformstest\winformstest.csproj”。
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/winformscominterop/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/winformscominterop/index.json 2285 毫秒
info : 正在还原 E:\dotnet\winformstest\winformstest.csproj 的包...
info : 包“WinFormsComInterop”与项目“E:\dotnet\winformstest\winformstest.csproj”中指定的所有框架均兼容。
info : 包“WinFormsComInterop”(版本为 0.2.9)的 PackageReference 已添加到文件“E:\dotnet\winformstest\winformstest.csproj”
。
info : 将资产文件写入磁盘。路径: E:\dotnet\winformstest\obj\project.assets.json
log  : 已还原 E:\dotnet\winformstest\winformstest.csproj (用时 61 ms)。
PS E:\dotnet\winformstest> dotnet run
PS E:\dotnet\winformstest> dotnet publish -r win-x64 -p:PublishTrimmed=true
用于 .NET 的 Microsoft (R) 生成引擎版本 17.1.1+a02f73656
版权所有(C) Microsoft Corporation。保留所有权利。

  正在确定要还原的项目…
  已还原 E:\dotnet\winformstest\winformstest.csproj (用时 162 ms)。
C:\Program Files\dotnet\sdk\6.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(176,5): error NETSDK1175: 启用剪裁时，不支持或不推荐使用 Windows 窗体。请转到 https://aka.ms/dotnet-illink/windows-forms 以 了解详细信息。 [E:\dotnet\winformstest\winformstest.csproj]

**Comment by kant2002** [comment]
As stated in error message, MS do not support AOT and trimming yet, at the same time, if you want experiment, you can add
```
<_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
```

That should unblock you.

**Comment by zhzhwcn** [comment]
It worked, thank you.
