### ISSUE TITLE
Failed to compile with NativeAOT .NET 7.0

### ISSUE THREAD

**Issue by xoofx** [kant2002/WinFormsComInterop#48]
Hey,

I was trying to use it on a .NET 7 + NativeAOT and dotnet publish generates the following warning:

```
ILC: Method '[SimpleProgramChange]SimpleProgramChange.SimpleProgramChangeController.CreateView()' will always throw because: Failed to load assembly 'System.Windows.Forms'
```

And it crashes at runtime indeed. 

I had also to remove the initialization of `WinFormsComInterop` (Package `0.3.2`) as I saw it [here](https://github.com/kant2002/WinFormsComInterop/blob/2544da64e3b0d276129d9945e8afde1602f220b8/samples/SampleWindowsForms/Program.cs#L16-L18)

Any clue?

**Comment by kant2002** [comment]
SampleWindowsForms was a bit outdated (I did update). Couple questions
- Are you using `net7.0-windows`?
- is it possible that you have dependency on other library?

**Comment by xoofx** [comment]
> Are you using net7.0-windows?

Yep.

> is it possible that you have dependency on other library?

I was using directly winforms and the UserControl, so pretty basic.

But don't worry, that was for testing. Probably not gonna use winforms anyway.

I will close it for now. Thanks!

**Comment by kant2002** [comment]
That's pretty strange, since I did try that on different apps, and never seen this issue. 
Also to let you know that I soon will have update for WinForms + WebView2 + Blazor, so maybe that would be more interesting to you.

**Comment by kant2002** [comment]
Also what OS you are try to compile? I assume that's windows?

**Comment by xoofx** [comment]
> Also what OS you are try to compile? I assume that's windows?

Yeah, Windows.

> That's pretty strange, since I did try that on different apps, and never seen this issue.
> Also to let you know that I soon will have update for WinForms + WebView2 + Blazor, so maybe that would be more interesting to you.

My setup is a bit unusual, as it was to test this within a NativeAOT library (and not an exe), though I would not think that would matter, the error is coming from ILC, like it's not even able to locate the assembly, dunno, but weird... anyway, I don't want to bother you with this! 😉

**Comment by kant2002** [comment]
Take a look at this sample https://github.com/kant2002/WinFormsComInterop/tree/main/samples/HostedWindowsForms. I think you was missing `--self-contained` when publish application.
