### ISSUE TITLE
BlazorHybrid demo does not work

### ISSUE THREAD

**Issue by Martin12350** [kant2002/WinFormsComInterop#67]
Copying the full repo and trying to build the BlazorHybrid demo fails with 219 errors. Well happens.

Isolating only the BlazorHybrid demo, removing reference to the project, and adding Nuget WinFormsComInterop (0.4.3) it is finally possible to build. A little bit broken CSS but not a big deal. Commented out /fetchdata is on purpose, I guess, since uncommenting that will crash with the following error:
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.

But the biggest issue is that it is not possible to **publish** as a native AOT.
When trying to do either in Visual Studio or with the dotnet command, both fails with an error:

```
Failed to load type 'BlazorHybrid.Counter' from assembly 'BlazorHybrid, Version=0.4.3.0, Culture=neutral, PublicKeyToken=null'
2> Internal.TypeSystem.TypeSystemException+TypeLoadException: Failed to load type 'BlazorHybrid.Counter' from assembly 'BlazorHybrid, Version=0.4.3.0, Culture=neutral, PublicKeyToken=null'
2>   at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID, String, String) in /_/src/coreclr/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 17
2>   at Internal.TypeSystem.ResolutionFailure.Throw() in /_/src/coreclr/tools/Common/TypeSystem/Common/ResolutionFailure.cs:line 93
2>   at Internal.TypeSystem.Ecma.EcmaModule.GetType(String, String, NotFoundBehavior) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 344
2>   at Internal.TypeSystem.ModuleDesc.GetType(String, String, Boolean ) in /_/src/coreclr/tools/Common/TypeSystem/Common/ModuleDesc.cs:line 35
2>   at Internal.TypeSystem.CustomAttributeTypeNameParser.ResolveCustomAttributeTypeDefinitionName(String, ModuleDesc, Boolean) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/CustomAttributeTypeNameParser.cs:line 261
2>   at Internal.TypeSystem.CustomAttributeTypeNameParser.GetTypeByCustomAttributeTypeName(ModuleDesc, String, Boolean , Func`4 ) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/CustomAttributeTypeNameParser.cs:line 76
2>   at ILCompiler.RdXmlRootProvider.ProcessTypeDirective(IRootingServiceProvider, ModuleDesc, XElement) in /_/src/coreclr/tools/aot/ILCompiler/RdXmlRootProvider.cs:line 98
2>   at ILCompiler.RdXmlRootProvider.ProcessAssemblyDirective(IRootingServiceProvider, XElement) in /_/src/coreclr/tools/aot/ILCompiler/RdXmlRootProvider.cs:line 83
2>   at ILCompiler.RdXmlRootProvider.AddCompilationRoots(IRootingServiceProvider) in /_/src/coreclr/tools/aot/ILCompiler/RdXmlRootProvider.cs:line 47
2>   at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1, NodeFactory, IEnumerable`1, ILProvider, DebugInformationProvider, DevirtualizationManager, IInliningPolicy, Logger) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 64
2>   at ILCompiler.ILScannerBuilder.ToILScanner() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScannerBuilder.cs:line 83
2>   at ILCompiler.Program.<Run>g__RunScanner|73_4(<>c__DisplayClass73_0&) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 884
2>   at ILCompiler.Program.Run(String[]) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 866
2>   at ILCompiler.Program.Main(String[]) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 1150
```

Am I missing something? Is there some specific order of operations that has to be followed? Any help is appreciated.

**Comment by kant2002** [comment]
Sorry, it was my mistake. See https://github.com/kant2002/WinFormsComInterop/commit/797396d80e044095ee45a3c932eae56b697e9274

If you want fetch, I assume you need to add new type here 
https://github.com/kant2002/WinFormsComInterop/blob/main/samples/BlazorHybrid/rd.xml

And maybe some additional things for HttpClient, you have to test. Unfortunately currently Blazor Hybrid require such laborious work.

**Comment by Martin12350** [comment]
Oh my... I was banging my head on the keyboard, I tried to create a new project from scratch, changing properties, versions, etc.
And it was yelling the whole time "failed to load assembly", just because it was missing one word.
Thank you for the fix :)

**Comment by kant2002** [comment]
Don't worry. That's normal situation, this thing a bit complicated to learn from first stab. Take your time, I bet NativeAOT eventually make your app small !

**Comment by Martin12350** [comment]
I really like the idea of native AOT and their advantages. The only problem now is that a lot of things are not supported yet or need a lot of tweaking. Which leads me to another question - not sure if I should write here, spin another thread, or maybe discuss on another platform (Discord maybe?). Anyway, I will try. 

Is it possible to deploy it as a single file? PublishSingleFile and NativeAOT properties cannot be used together.
Publishing now results in one .exe, few DLLs (found out that only webview2loader.dll is needed) and wwwroot folder.
I was able to embed the wwwroot inside the app, however this bug appeared [#1333 issue](https://github.com/dotnet/extensions/issues/1333), I peeked into .exe copied the manifest, fixed the error and manually forced it back in the app. 
It obviously works, but it is tedious, and I cannot imagine doing all the time over when adding some new files.

Maybe I want a lot of things ;)

**Comment by Martin12350** [comment]
Found out solution for the [#1333 issue](https://github.com/dotnet/extensions/issues/1333).
For those who would like to embed wwwroot into the application, it is necessary to add those lines in the .csproj
```
<ItemGroup>
  <EmbeddedResource Update="MainForm.resx" ExcludeFromManifest="true" />
</ItemGroup>
```
Big help from this thread [#31107](https://github.com/dotnet/aspnetcore/pull/31107#pullrequestreview-617743002)

The final step is to figure out if it is possible to embed all those dlls :)

**Comment by kant2002** [comment]
So you embed whole `wwwroot`, that's really nice. Regarding single file and NativeAOT. As you probably figure out that's mutually exclusive things. And what even Single file means for NativeAOT, some "magic" packer? it would not work. NativeAOT in a sense alreade single file.

**Comment by Martin12350** [comment]
I fell into the rabbit hole. Even the name `PublishSingleFile` is not truly a single file, and more or less dlls are there (depending on the project size, obviously). But with combination `IncludeNativeLibrariesForSelfExtract` publishing will result in really only one single file. And I would like to achieve the same or similar with AOT. To have only one single file. But so far, no luck.

**Comment by kant2002** [comment]
You have to package that in single file yourself. This scenario does not supported.

**Comment by Martin12350** [comment]
Yep, I thought that. But do you have some guide or something to steer me the right way?
Should I embed it the same way as the folder? Or used something like ILmerge? Would Costura.Fody work?
What is the way to go?

**Comment by kant2002** [comment]
I would try to look at https://github.com/MichalStrehovsky/PublishAotCompressed . I think your solution lays in unmanaged land of different kind of packers like UPX or something like that. Fody is for managed assemblies, but you want to pack unmanaged DLL into your EXE.

**Comment by Martin12350** [comment]
Will definitely try and check. Thanks a lot for your help :)
