### ISSUE TITLE
SourceGenerator doesn’t run at design time in its own solution

### ISSUE THREAD

**Issue by wjk** [kant2002/WinFormsComInterop#9]
While working on #8, I have discovered that, for some reason, the source generator does not run when it is resolved as a project reference during design-time builds. Its entry under the Dependencies node states “This generator is not generating files.” As such, the files in the WinFormsComInterop project display spurious errors about missing types and members. Note that the source generator does run correctly when the solution is built.

**Comment by kant2002** [comment]
Do you use project by referencing from disk, or using from Nuget. If from disk, then it's https://github.com/dotnet/roslyn/issues/54073
